# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Report CPU Architecture and Compiler
#'
#' @return A constant direct created at compile-time describing
#' the extent of AVX instructions (512 bit, 128 bit, or none)
#' and compiler use where currently recognised are MSC (unlikely
#' for R), GCC, Clang, or \sQuote{other}.
getArchictectureStatus <- function() {
    .Call(`_rVictis_getArchictectureStatus`)
}

jaccard_coeff_parallel <- function(idx) {
    .Call(`_rVictis_jaccard_coeff_parallel`, idx)
}

jaccard_coeff <- function(idx) {
    .Call(`_rVictis_jaccard_coeff`, idx)
}

jaccard_coeff_true_parallel <- function(idx, threshold = 0L) {
    .Call(`_rVictis_jaccard_coeff_true_parallel`, idx, threshold)
}

knn_annoy <- function(mat, K = 100L, trees = 150L) {
    .Call(`_rVictis_knn_annoy`, mat, K, trees)
}

